BaseUrl= "https://syui.cf/hugo-theme-air/"
LanguageCode= "en-US"
Title= "Hugo Theme Air"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true

[author]
  name = "Murph-Ferg"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[params]
  description = "All things AWS & Azure"
  cover = "images/user.jpg"
  author = "Murph-Ferg"
  authorlocation = ""
  authorwebsite = "https://www.engineer.cloud"
  bio= "my bio"
  logo = "images/user.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "murphferg"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  mainSections = ["post"]
